### ISSUE TITLE
Open in a new tab

### ISSUE THREAD

**Issue by FrankTCtct** [jnawk/aws-electron#37]
As a user with a laptop, I would like to be able to open a link in a new tab.

**Comment by jnawk** [comment]
Middle click does it.

**Comment by FrankTCtct** [comment]
I don't have a middle mouse button! :(

**Comment by jnawk** [comment]
Context menu it is.  I need that for a couple other features I've got on the wish list in my head anyway.

**Comment by jnawk** [comment]
Apparently control-click does it too.
